name: Main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install noirup
        run: |
            curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
            echo "${HOME}/.nargo/bin" >> $GITHUB_PATH
      - name: Install nargo with noirup
        run: | 
            noirup
            nargo --version
      - name: Run tests
        run: nargo test --show-output